// Reads the locally-seeded SQLite database and emits a D1-ready seed.sql of the
// static game content (game, characters, clues, scripted announcements).
// Runtime tables (discoveries, votes) are intentionally excluded.
//
//   npm run db:seed && npx tsx scripts/export-d1-seed.ts > cf-seed.sql

import { PrismaClient } from "@prisma/client";
import { PrismaLibSQL } from "@prisma/adapter-libsql";

const adapter = new PrismaLibSQL({ url: "file:./prisma/dev.db" });
const prisma = new PrismaClient({ adapter });

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "1" : "0";
  return `'${String(v).replace(/'/g, "''")}'`;
};

function insert(table: string, cols: string[], rows: Record<string, unknown>[]) {
  const lines: string[] = [];
  for (const r of rows) {
    const values = cols.map((c) => q(r[c])).join(", ");
    lines.push(`INSERT OR IGNORE INTO "${table}" (${cols.map((c) => `"${c}"`).join(", ")}) VALUES (${values});`);
  }
  return lines.join("\n");
}

async function main() {
  const games = await prisma.game.findMany();
  const characters = await prisma.character.findMany({ orderBy: { sortOrder: "asc" } });
  const clues = await prisma.clue.findMany({ orderBy: [{ phase: "asc" }, { code: "asc" }] });
  const announcements = await prisma.announcement.findMany({ orderBy: { sortOrder: "asc" } });

  const out: string[] = [
    "-- Dead in the Water — seed data for Cloudflare D1.",
    "-- Generated by scripts/export-d1-seed.ts. Apply after 0001_init.sql.",
    "",
    insert("Game", ["id", "name", "status", "currentPhase", "activeVoteRound"], games),
    "",
    insert(
      "Character",
      ["id", "gameId", "personaName", "realName", "role", "loginCode", "isGameMaster", "prop", "avatarColor", "sheet", "sortOrder"],
      characters,
    ),
    "",
    insert(
      "Clue",
      ["id", "gameId", "code", "title", "content", "location", "phase", "tag", "token"],
      clues,
    ),
    "",
    insert(
      "Announcement",
      ["id", "gameId", "kind", "title", "body", "phase", "sortOrder", "isScripted", "isReleased"],
      announcements,
    ),
    "",
  ];

  process.stdout.write(out.join("\n"));
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
